# Generated by Django 3.0.2 on 2020-01-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
